version: "3.8"
services:
  mail:
    image: bytemark/smtp
    restart: always

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
    env_file: .env
    volumes:
      - geoip:/usr/share/GeoIP

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
    restart: always

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
      - $PWD/clickhouse/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml:ro
      - $PWD/clickhouse/docker_related_user_config.xml:/etc/clickhouse-server/users.d/docker_related_user_config.xml:ro
    tmpfs:
      - /var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - internal
    restart: always

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
      - traefik
    env_file: .env
    networks:
      - internal
      - web
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    volumes:
      - geoip:/geoip:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.rule=Host(`127.0.0.1.nip.io`)" # TODO: Change with your own domain
      - "traefik.http.routers.plausible.entrypoints=web" # websecure
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v2.2
    container_name: traefik
    ports:
      - "80:80"
      #- "443:443" https
      - "8080:8080" # TODO: Remove in production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/traefik/acme.json:/acme.json
    restart: always
    networks:
      - web

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

networks:
  web:
    external: true
  internal:
    external: false
