version: "3.8"
services:
  mail:
    image: bytemark/smtp
    restart: always

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
    env_file: .env
    volumes:
      - geoip:/usr/share/GeoIP

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
    restart: always

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml:ro
      - ./clickhouse-user-config.xml:/etc/clickhouse-server/users.d/docker_related_user_config.xml:ro
    tmpfs:
      - /var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - internal
    restart: always

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
      - traefik
    env_file: .env
    networks:
      - internal
      - web
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    volumes:
      - geoip:/geoip:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.rule=Host(`${DOMAIN}`)" # TODO: Change with your own domain
      - "traefik.http.routers.plausible.entrypoints=websecure"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v2.2
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # TODO: Remove in production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    restart: always
    networks:
      - web
    command:
      - "--api.insecure=true" # TODO: Remove in production
      - "--api.dashboard=true" # TODO: Remove in production
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certResolver=default"
      - "--certificatesresolvers.default.acme.tlschallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.default.acme.email=${ADMIN_USER_EMAIL}" # TODO: Change with your own email
      - "--certificatesresolvers.default.acme.storage=acme.json"

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

networks:
  web:
    external: true
  internal:
    external: false
